extends RefCounted
## The mascot's part layout, in master SVG units (viewBox 380 190 1290 1650).
##
## GENERATED by scripts/art/brand/build_bonehead_brand.py from
## art/source/bonehead_mascot.svg. Do not edit by hand.

const VIEW_BOX := Rect2(380, 190, 1290, 1650)
## The art/mascot_<part>.svg files import at this svg/scale (their .import files).
const IMPORT_SCALE: float = 0.6
## Each part's rect: its SVG's viewBox, so a texture of rect.size * IMPORT_SCALE px.
const PARTS: Dictionary = {
	&"shadow": Rect2(751, 1643, 800, 191),
	&"body": Rect2(672, 534, 706, 1170),
	&"cups": Rect2(503, 662, 1040, 322),
	&"ink": Rect2(430, 238, 1188, 1533),
	&"mouth": Rect2(891, 947, 268, 129),
	&"mouth_open": Rect2(928, 976, 192, 128),
	&"eyes": Rect2(853, 766, 341, 144),
	&"happy_eyes": Rect2(837, 749, 373, 142),
}
## Body, cups and ink together: the figure the jump and the vibe move.
const FIGURE_BOX := Rect2(430, 238, 1188, 1533)
## The site's transform-origin 50% 100%: the feet.
const FEET := Vector2(1024, 1771)
const SHADOW_CENTER := Vector2(1151, 1738.5)
## Both eyes sit on this line, so a blink scales the eyes around it.
const EYE_LINE_Y: float = 838
const CUP_LEFT := Vector2(591.62, 823.81)
const CUP_RIGHT := Vector2(1455.84, 823.31)
